export const PROJECTS = [
  {
    id: 1,
    src: "/solemates.avif",
    title: "Sole Mates",
    category: "Web Development",
    date: "August 23, 2026",
    desc: "SoleMates is a modern footwear brand website inspired by the connection between Ethiopian craftsmanship and contemporary style.",
    github: "https://github.com/khalidabdifetah9/solemates.git",
    live: "https://solemates.vercel.app/",
  },
  {
    id: 2,
    src: "/arch.avif",
    title: "Arch",
    category: "Web Development",
    date: "January 23, 2025",
    desc: "ARCH is a modern creative studio website designed to showcase digital experiences, development, creative direction.",
    github: "https://github.com/khalidabdifetah9/Arch.git",
    live: "https://arch-two-gilt.vercel.app/",
  },
  {
    id: 3,
    src: "/crave.avif",
    title: "Crave & CO.",
    category: "Web Development",
    date: "January 23, 2025",
    desc: "Crave & Co. is a modern restaurant website designed to create a bold and inviting digital experience around food, atmosphere, and the brand.",
    github: "https://github.com/khalidabdifetah9/Crave-Co..git",
    live: "https://crave-jade.vercel.app/",
  },
  {
    id: 4,
    src: "/court.avif",
    title: "Addis Ababa Court System",
    category: "Web Development",
    date: "January 23, 2025",
    desc: "A digital court management platform designed to simplify and organize judicial processes.",
    github: "https://github.com/khalidabdifetah9/court-system.git",
    live: "https://courtsystemkalid.vercel.app/",
  },
  {
    id: 5,
    src: "/every.avif",
    title: "Every Biomedicals",
    category: "UI/UX Design",
    date: "February 14, 2026",
    desc: "A biomedical products and services platform built to make healthcare equipment and medical solutions easier to discover and manage..",
    github: "https://github.com/khalidabdifetah9/Public_Every.git",
    live: "https://everybiomedicalkalid.vercel.app/",
  },
  {
    id: 6,
    src: "/agri_market.avif",
    title: "Agri Market",
    category: "Web Development",
    date: "June 18, 2026",
    desc: "Agri-Market is a digital agricultural marketplace designed to connect farmers and buyers in one platform.",
    github: "https://github.com/khalidabdifetah9/Agri-Market.git",
    live: "https://agrimarketkalid.vercel.app/",
  },
  {
    id: 7,
    src: "/zewari.avif",
    title: "Zewari Distribution Saas",
    category: "EdTech",
    date: "March 29, 2024",
    desc: "Zewari Distribution is a SaaS platform designed to help distribution businesses manage their day-to-day operations from a single, centralized system.",
    github: "#",
    live: "https://zewari.vercel.app/",
  },
];
