export const PROJECTS = [
  {
    id: 1,
    src: "/agrimar.png",
    title: "Agri-Market",
    category: "Web Development",
    date: "August 23, 2026",
    desc: "A digital agricultural marketplace connecting farmers, buyers, and agricultural businesses in one platform.",
    github: "https://github.com/khalidabdifetah9/Agri-Market.git",
    live: "https://agrimarketkalid.vercel.app/",
  },
  {
    id: 2,
    src: "/court.png",
    title: "Addis Ababa Court System",
    category: "Web Development",
    date: "January 23, 2025",
    desc: "A digital court management platform designed to simplify and organize judicial processes.",
    github: "https://github.com/khalidabdifetah9/court-system.git",
    live: "https://courtsystemkalid.vercel.app/",
  },
  {
    id: 3,
    src: "/every.png",
    title: "Every Biomedicals",
    category: "UI/UX Design",
    date: "February 14, 2026",
    desc: "A biomedical products and services platform built to make healthcare equipment and medical solutions easier to discover and manage..",
    github: "https://github.com/khalidabdifetah9/Public_Every.git",
    live: "https://everybiomedicalkalid.vercel.app/",
  },
  {
    id: 4,
    src: "/fisum.png",
    title: "Aleph Jobs",
    category: "Web Development",
    date: "June 18, 2026",
    desc: "A job discovery platform connecting job seekers with employment opportunities.",
    github: "https://github.com/khalidabdifetah9/aleph_public.git",
    live: "https://alephjobsskalid.vercel.app/",
  },
  {
    id: 5,
    src: "/kidslearn.png",
    title: "Kids Learnig Website",
    category: "EdTech",
    date: "March 29, 2024",
    desc: "An interactive learning platform designed to make education more engaging and enjoyable for children",
    github: "#",
    live: "#",
  },
  {
    id: 6,
    src: "/medFinder.png",
    title: "FindMed",
    category: "Healthcare AI",
    date: "November 7, 2024",
    desc: "A healthcare discovery platform designed to help people find medical services and healthcare providers more easily",
    github: "#",
    live: "#",
  },
];
