import React from "react";

export const metadata = {
  title: "Punto",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  },
};

const Name = () => {

    
  return <></>;
};

export default Name;
